"""names

Revision ID: 050af6e8f814
Revises: 23e568e67d3c
Create Date: 2019-09-18 16:42:21.873200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050af6e8f814'
down_revision = '23e568e67d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
