"""user

Revision ID: dd131f981676
Revises: 050af6e8f814
Create Date: 2019-09-18 21:23:57.546768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd131f981676'
down_revision = '050af6e8f814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'username')
    # ### end Alembic commands ###
